# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1 import inference_pb2 as api_dot_v1_dot_inference__pb2


class InferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InferenceCall = channel.unary_unary(
                '/inference.v1.Inference/InferenceCall',
                request_serializer=api_dot_v1_dot_inference__pb2.Input_data_for_inference.SerializeToString,
                response_deserializer=api_dot_v1_dot_inference__pb2.Output_data_for_inference.FromString,
                )


class InferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InferenceCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InferenceCall': grpc.unary_unary_rpc_method_handler(
                    servicer.InferenceCall,
                    request_deserializer=api_dot_v1_dot_inference__pb2.Input_data_for_inference.FromString,
                    response_serializer=api_dot_v1_dot_inference__pb2.Output_data_for_inference.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.v1.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Inference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InferenceCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference.v1.Inference/InferenceCall',
            api_dot_v1_dot_inference__pb2.Input_data_for_inference.SerializeToString,
            api_dot_v1_dot_inference__pb2.Output_data_for_inference.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
