# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi/v1/inference.proto\x12\x0cinference.v1\"(\n\x18Input_data_for_inference\x12\x0c\n\x04text\x18\x01 \x01(\t\"8\n\x19Output_data_for_inference\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\r2o\n\tInference\x12\x62\n\rInferenceCall\x12&.inference.v1.Input_data_for_inference\x1a\'.inference.v1.Output_data_for_inference\"\x00\x42!Z\x1fgithub.com/Kazuki-Ya/api/log_v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037github.com/Kazuki-Ya/api/log_v1'
  _INPUT_DATA_FOR_INFERENCE._serialized_start=40
  _INPUT_DATA_FOR_INFERENCE._serialized_end=80
  _OUTPUT_DATA_FOR_INFERENCE._serialized_start=82
  _OUTPUT_DATA_FOR_INFERENCE._serialized_end=138
  _INFERENCE._serialized_start=140
  _INFERENCE._serialized_end=251
# @@protoc_insertion_point(module_scope)
