// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: api/v1/inference.proto

package log_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputDataForInference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *InputDataForInference) Reset() {
	*x = InputDataForInference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputDataForInference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputDataForInference) ProtoMessage() {}

func (x *InputDataForInference) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputDataForInference.ProtoReflect.Descriptor instead.
func (*InputDataForInference) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *InputDataForInference) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type OutputDataForInference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text  string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Label uint32 `protobuf:"varint,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *OutputDataForInference) Reset() {
	*x = OutputDataForInference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_inference_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputDataForInference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputDataForInference) ProtoMessage() {}

func (x *OutputDataForInference) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inference_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputDataForInference.ProtoReflect.Descriptor instead.
func (*OutputDataForInference) Descriptor() ([]byte, []int) {
	return file_api_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *OutputDataForInference) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OutputDataForInference) GetLabel() uint32 {
	if x != nil {
		return x.Label
	}
	return 0
}

var File_api_v1_inference_proto protoreflect.FileDescriptor

var file_api_v1_inference_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x2e, 0x0a, 0x18, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x45, 0x0a, 0x19, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x32, 0x6f, 0x0a,
	0x09, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x0d, 0x49, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x26, 0x2e, 0x69, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x1a, 0x27, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x66,
	0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x00, 0x42, 0x21,
	0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x61, 0x7a,
	0x75, 0x6b, 0x69, 0x2d, 0x59, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6f, 0x67, 0x5f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_inference_proto_rawDescOnce sync.Once
	file_api_v1_inference_proto_rawDescData = file_api_v1_inference_proto_rawDesc
)

func file_api_v1_inference_proto_rawDescGZIP() []byte {
	file_api_v1_inference_proto_rawDescOnce.Do(func() {
		file_api_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_inference_proto_rawDescData)
	})
	return file_api_v1_inference_proto_rawDescData
}

var file_api_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_inference_proto_goTypes = []interface{}{
	(*InputDataForInference)(nil),  // 0: inference.v1.Input_data_for_inference
	(*OutputDataForInference)(nil), // 1: inference.v1.Output_data_for_inference
}
var file_api_v1_inference_proto_depIdxs = []int32{
	0, // 0: inference.v1.Inference.InferenceCall:input_type -> inference.v1.Input_data_for_inference
	1, // 1: inference.v1.Inference.InferenceCall:output_type -> inference.v1.Output_data_for_inference
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_inference_proto_init() }
func file_api_v1_inference_proto_init() {
	if File_api_v1_inference_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_inference_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputDataForInference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_inference_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputDataForInference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_inference_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_inference_proto_goTypes,
		DependencyIndexes: file_api_v1_inference_proto_depIdxs,
		MessageInfos:      file_api_v1_inference_proto_msgTypes,
	}.Build()
	File_api_v1_inference_proto = out.File
	file_api_v1_inference_proto_rawDesc = nil
	file_api_v1_inference_proto_goTypes = nil
	file_api_v1_inference_proto_depIdxs = nil
}
